### ISSUE TITLE
take advantage of SPV_KHR_8bit_storage

### ISSUE THREAD

**Issue by dneto0** [google/clspv#169] opened 2018-08-09 13:36 UTC
The 8bit storage extension allows reading and writing 8bit values, provided those values are immediately converted to (or from) a wider type. It does not enable 8bit arithmetic for example.

http://htmlpreview.github.io/?https://github.com/KhronosGroup/SPIRV-Registry/blob/master/extensions/KHR/SPV_KHR_8bit_storage.html

**Comment by dneto0** [comment] 2018-08-09 13:37
This should be similar to -f16bit_storage

**Comment by alan-baker** [comment] 2019-03-06 16:05
Duplicate of #280

**Closed by alan-baker** 2019-03-06 16:05 UTC
Labels: enhancement
