### ISSUE TITLE
Division by zero crash in ReplacePointerBitcastPass.cpp

### ISSUE THREAD

**Issue by Jasper-Bekkers** [google/clspv#98] opened 2017-10-19 12:47 UTC
Repro:

```
typedef struct 
{
  float x, y, z, w;
} MyStruct;

__attribute__((reqd_work_group_size(1, 1, 1)))
__kernel void myTest(__global float4 *a1)
{
  __global MyStruct* jasper = (__global MyStruct*)a1;
  jasper->x = 0;
  jasper->y = 1;
  jasper->z = 2;
  jasper->w = 3;
}
```

Crash happens later in `CalculateNumIter` but essentially originates in 
https://github.com/google/clspv/blob/master/lib/ReplacePointerBitcastPass.cpp#L145 because `DstTyBitWidth` is zero.

**Comment by Jasper-Bekkers** [comment] 2017-10-19 12:53
Having the struct in there seems to be the cause of the problem, since casting to `float` works properly.

```
__attribute__((reqd_work_group_size(1, 1, 1)))
__kernel void myTest(__global float4 *a1)
{
  __global float* jasper = (__global float*)a1;
  jasper[0] = 0;
  jasper[1] = 1;
  jasper[2] = 2;
  jasper[3] = 3;
}
```

**Comment by dneto0** [comment] 2017-10-19 14:39
Yes, this looks a lot like a duplicate of #37 

The ReplacePointerBitcasts pass so far mainly deals with conversions between pointers to vectors and pointers to scalars.   It hasn't dealt with structs yet, but that would be good to fix.

I bet it's falling into a codepath where it expected the pointee type was expected to be a vector.  Then it falls flat on its face.

**Comment by dneto0** [comment] 2018-05-03 22:08
FYI:  In LLVM you get the size of a struct via an API in the llvm::DataLayout object.  You get that object from the llvm::Module.

The ReplacePointerBitcasts code is .... very subtle and complex.

**Comment by dneto0** [comment] 2018-06-15 16:06
This is now fixed.  I've retested with latest clspv from master.

I think it was https://github.com/google/clspv/pull/138 that fixed it.  That PR generalized some of the replace-pointer-bitcasts algorithms to handle more cases where the pointer points at an  aggregate type like a struct or array. 

The example compiles down to:
```
               OpCapability Shader
               OpCapability VariablePointers
               OpExtension "SPV_KHR_storage_buffer_storage_class"
               OpExtension "SPV_KHR_variable_pointers"
               OpMemoryModel Logical GLSL450
               OpEntryPoint GLCompute %19 "myTest"
               OpExecutionMode %19 LocalSize 1 1 1
               OpSource OpenCL_C 120
               OpDecorate %_runtimearr_v4float ArrayStride 16
               OpMemberDecorate %_struct_4 0 Offset 0
               OpDecorate %_struct_4 Block
               OpDecorate %18 DescriptorSet 0
               OpDecorate %18 Binding 0
      %float = OpTypeFloat 32
    %v4float = OpTypeVector %float 4
%_runtimearr_v4float = OpTypeRuntimeArray %v4float
  %_struct_4 = OpTypeStruct %_runtimearr_v4float
%_ptr_StorageBuffer__struct_4 = OpTypePointer StorageBuffer %_struct_4
       %uint = OpTypeInt 32 0
       %void = OpTypeVoid
          %8 = OpTypeFunction %void
%_ptr_StorageBuffer_float = OpTypePointer StorageBuffer %float
     %uint_0 = OpConstant %uint 0
    %float_0 = OpConstant %float 0
     %uint_1 = OpConstant %uint 1
    %float_1 = OpConstant %float 1
     %uint_2 = OpConstant %uint 2
    %float_2 = OpConstant %float 2
     %uint_3 = OpConstant %uint 3
    %float_3 = OpConstant %float 3
         %18 = OpVariable %_ptr_StorageBuffer__struct_4 StorageBuffer
         %19 = OpFunction %void None %8
         %20 = OpLabel
         %21 = OpAccessChain %_ptr_StorageBuffer_float %18 %uint_0 %uint_0 %uint_0
               OpStore %21 %float_0
         %22 = OpAccessChain %_ptr_StorageBuffer_float %18 %uint_0 %uint_0 %uint_1
               OpStore %22 %float_1
         %23 = OpAccessChain %_ptr_StorageBuffer_float %18 %uint_0 %uint_0 %uint_2
               OpStore %23 %float_2
         %24 = OpAccessChain %_ptr_StorageBuffer_float %18 %uint_0 %uint_0 %uint_3
               OpStore %24 %float_3
               OpReturn
               OpFunctionEnd
```

**Closed by dneto0** 2018-06-15 16:06 UTC
