### ISSUE TITLE
"Having 8 components for TypeVector requires the Vector16 capability"

### ISSUE THREAD

**Issue by fused** [google/clspv#652] opened 2020-10-16 15:20 UTC
Using the experimental long vector support,

```
__kernel void kernel1(
	__global float* restrict state
)
{
	float8 vec;
	int id = 0;
	if(id == 0)
	{
		vec = (float8)(1.0f);
	}

	state[0] = vec.s0;
}
```
spirv-val produces this error:

```
error: line 34: Having 8 components for TypeVector requires the Vector16 capability
  %v8float = OpTypeVector %float 8
```
When the Vector16 capability is added, it works.

**Comment by mantognini** [comment] 2020-10-16 16:34
This kernel is not yet fully supported by the experimental support for long-vector types described in #613. Clspv actually emits several "Value not handled" debug messages. I would consider this a duplicate of #613 as we plan to introduce more features to support that kind of code under that issue.

**Comment by fused** [comment] 2020-10-16 17:28
Thank you for the reply. I figured it would be related. I'm very much looking forward to it.

**Comment by alan-baker** [comment] 2020-10-20 13:03
Closing as duplicate of #613.

**Closed by alan-baker** 2020-10-20 13:03 UTC
