### ISSUE TITLE
MSVC 2017 compile failed

### ISSUE THREAD

**Issue by pdsharma0** [google/clspv#153] opened 2018-06-21 03:54 UTC
I am seeing a bunch of warnings treated as errors using Visual Studio 2017 15.7.4 version.  The culprit is **SPIRVProducerPass.cpp** and disabling these warnings in **lib/CMakelists.txt** gets me the clspv.exe.

```
 if (MSVC)
   set_source_files_properties("${CMAKE_CURRENT_SOURCE_DIR}/SPIRVProducerPass.cpp"
-    PROPERTIES COMPILE_FLAGS "/Wall /WX /wd4710 /wd4820 /wd4625 /wd4626 /wd5026 /wd5027 /wd4061 /wd4711 /wd4996 /wd4530 /wd4577 /wd4514 /wd4365 /wd4987 /wd4774 /wd4623 /wd4571"
+    PROPERTIES COMPILE_FLAGS "/Wall /WX /wd4710 /wd4820 /wd4625 /wd4626 /wd5026 /wd5027 /wd4061 /wd4711 /wd4996 /wd4530 /wd4577 /wd4514 /wd4365 /wd4987 /wd4774 /wd4623 /wd4571 /wd4242 /wd4244 /wd4189 /wd4596 /wd4457 /wd5039 /wd5045"
   )
 endif()
```

**Comment by dneto0** [comment] 2018-06-21 18:15
Thanks for the report. 

MSVC is not my main development environment.  I have version 15.5.1
I will try downloading an updated VisualStudio and see if I can reproduce the issue. If it's easy enough to fix the code I'll fix the code.

**Comment by pdsharma0** [comment] 2018-06-22 04:57
No hurries, thanks!

I also noticed a lot of INTERNAL COMPILATION ERRORS while building LLVM on MSVC which I think is being caused by my CPU pegging at 100%. Building the targets independently seems to work but takes some manual effort.

**Comment by dneto0** [comment] 2018-06-22 14:03
Thanks for your patience.  I downloaded the updated VS2017... but am now away from that machine until Monday at least.

Looking at the list:
  4242:  type mismatch loss of data on assignment....   Might turn this off
  4244: same, but for param passing.  Same
  4189: Local variable initialized but not reference.   Plan to fix that
  4596:   'identifier': illegal qualified name in member declaration.....  Hm. That seems bad.  Should fix
  5039:  'function': pointer or reference to potentially throwing function passed to extern C function under -EHc. Undefined behavior may occur if this function throws an exception.
     By google style guide I don't use exceptions.  Likely will disable this warning

  5045: Warn where a Spectre mitigation would have been inserted if you supplied /Qspectre
This one is really interesting. See https://blogs.msdn.microsoft.com/vcblog/2018/04/20/spectre-diagnostic-in-visual-studio-2017-version-15-7-preview-4/  
   I will disable this warning.

**Comment by pdsharma0** [comment] 2018-06-22 23:17
Thanks for looking into it.

**4242**, **4244** and **4189** are easy to fix though:

```
diff --git a/lib/SPIRVProducerPass.cpp b/lib/SPIRVProducerPass.cpp
index 8568bc1..d125f4d 100644
--- a/lib/SPIRVProducerPass.cpp
+++ b/lib/SPIRVProducerPass.cpp
@@ -181,13 +181,13 @@ struct SPIRVInstruction {
     }
   }

-  uint16_t getWordCount() const { return WordCount; }
+  uint32_t getWordCount() const { return WordCount; }
   uint16_t getOpcode() const { return Opcode; }
   uint32_t getResultID() const { return ResultID; }
   ArrayRef<SPIRVOperand *> getOperands() const { return Operands; }

 private:
-  uint16_t WordCount;
+  uint32_t WordCount;
   uint16_t Opcode;
   uint32_t ResultID;
   SmallVector<SPIRVOperand *, 4> Operands;
@@ -724,7 +724,7 @@ void SPIRVProducerPass::GenerateLLVMIRInfo(Module &M, const DataLayout &DL) {
       if (GVList.size() > 0) {
         assert(GVList.size() == 1);
         const auto *GV = GVList[0];
-        const size_t constants_byte_size =
+        const auto constants_byte_size =
             (DL.getTypeSizeInBits(GV->getInitializer()->getType())) / 8;
         const size_t kConstantMaxSize = 65536;
         if (constants_byte_size > kConstantMaxSize) {
@@ -2736,7 +2736,7 @@ void SPIRVProducerPass::GenerateFuncPrologue(Function &F) {
               << "kernel," << F.getName() << ",arg," << name << ",argOrdinal,"
               << old_index << ",argKind," << argKind << ",arrayElemSize,"
               << DL.getTypeAllocSize(
-                     fTy->getParamType(new_index)->getPointerElementType())
+                     fTy->getParamType((unsigned)new_index)->getPointerElementType())
               << ",arrayNumElemSpecId," << spec_id << "\n";
         } else {
           descriptorMapOut << "kernel," << F.getName() << ",arg," << name
@@ -2785,7 +2785,6 @@ void SPIRVProducerPass::GenerateFuncPrologue(Function &F) {
           GVarWithEmittedBindingInfo.insert(NewGV);

           SPIRVOperandList Ops;
-          SPIRVOperand *ArgIDOp = nullptr;
           uint32_t ArgID = 0;

           if (uses_binding) {
@@ -5053,7 +5052,6 @@ void SPIRVProducerPass::HandleDeferredInstruction() {
         Ops << MkId(lookupType(Call->getType()));

         for (Use &use : Call->arg_operands()) {
-          Value *val = use.get();
           Ops << MkId(VMap[use.get()]);
         }
```

**4596** actually needs a fix in LLVM's include\llvm\adt\ilist.h file. See : https://reviews.llvm.org/rL330639

**5039** and **5045** seem to occur together though and I didn't dig deeper into them.

**Comment by dneto0** [comment] 2018-06-28 20:30
I don't understand what the problem is with the WordCount.  I'll have to compile it myself to see.
SPIR-V limits word count in an instruction to 16 bit unsigned, so I'm motivated to keep it as a 16bit quantity.

The other changes look fine to me.

**Comment by dneto0** [comment] 2018-06-28 20:30
At the moment I'm pinned to a particular old version of both LLVM and Clang so I'll probably disable the warning for now.  I don't have time for a fresh upgrade at the moment.

**Comment by dneto0** [comment] 2018-06-28 22:16
I've merged some fixes.  Please take a look.
It works for me on my upgraded VS2017.  Please verify

**Comment by pdsharma0** [comment] 2018-07-01 05:49
Works perfect! Thank for the fixes.

**Closed** 2018-07-01 05:50 UTC
