### ISSUE TITLE
strange type on bitcast UNREACHABLE executed at clspv/lib/ReplacePointerBitcastPass.cpp:752!

### ISSUE THREAD

**Issue by kpet** [google/clspv#11] opened 2017-07-14 11:44 UTC
A few CL files from the [ARM Compute Library](https://github.com/ARM-software/ComputeLibrary) exhibit the following issue:

```
$ ./build/bin/clspv -DDATA_TYPE=float ComputeLibrary/src/core/CL/cl_kernels/convolution_layer.cl 
strange type on bitcast
UNREACHABLE executed at clspv/lib/ReplacePointerBitcastPass.cpp:752!
Aborted (core dumped)
```

Here's a couple that show the problem:
- [Convolution layer](https://github.com/ARM-software/ComputeLibrary/blob/db0e610fa90a4c7c534049792ee7fe143d46f72f/src/core/CL/cl_kernels/convolution_layer.cl), passing `-DDATA_TYPE=float`
- [Normalization Layer](https://github.com/ARM-software/ComputeLibrary/blob/db0e610fa90a4c7c534049792ee7fe143d46f72f/src/core/CL/cl_kernels/normalization_layer.cl)

**Comment by dneto0** [comment] 2017-07-14 14:38
I don't get the same results as you.

I have the ARM compute library at commit db0e610fa90a4c7c534049792ee7fe143d46f72f

Convolution layer:

It compiles for me, but does not validate.  Validation error is: 

`info: 172: Duplicate non-aggregate type declarations are not allowed. Opcode: 21
error: 1251: The Object type (OpTypePointer) in OpCompositeInsert does not match the type that results from indexing into the Composite (OpTypeRuntimeArray).`

Normalization layer:

Asserts out around line 835 of ReplacePointerBitcastPass.cpp.

The offending instruction is  `%12 = bitcast i8 addrspace(1)* %.elt to float addrspace(1)* `
That actually occurs twice, once in normalization_layer_cross_map, and another time in normalization_layer_in_map_1D.

Tracing the *map_1D case, there is a vload4 from a pointer derived from the `input` argument, which is declared as a TENSOR3D_DECLARATION.   In helpers.h that's defined as:
```
#define TENSOR3D_DECLARATION(name)   \
    __global uchar *name##_ptr,      \
    uint        name##_stride_x, \
    uint        name##_step_x,   \
    uint        name##_stride_y, \
    uint        name##_step_y,   \
    uint        name##_stride_z, \
    uint        name##_step_z,   \
    uint        name##_offset_first_element_in_bytes
```
The problem is that the base pointer is a pointer-to-uchar.

Vulkan does not support 8-bit loads and stores.   Loads and stores to 16bit types are only supported by the new VK_KHR_16bit_storage extension.

I'll mark this as "Invalid" since Clspv can't generate functioning code anyway.  But I will grant that the error message is *TERRIBLE*.

**Comment by dneto0** [comment] 2017-07-14 14:40
I filed https://github.com/google/clspv/issues/13 for improving error messages.

**Comment by dneto0** [comment] 2017-07-14 14:53
Closing in favour of the narrower but still valid #14

**Closed by dneto0** 2017-07-14 14:53 UTC
Labels: invalid
